name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
      -
        name: Install dependencies
        run: bun install
      -
        name: Build
        run: bun run build
      -
        name: Upload userscript artifact
        uses: actions/upload-artifact@v4
        with:
          name: anilist-extras.user.js
          path: dist/anilist-extras.user.js
      -
        name: Upload extension zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: anilist-extras.browser.zip
          path: dist/anilist-extras.browser-*.zip